Tryouts/Messaging-JS/src/TopicSubscriber.ts
Tryouts/Messaging-JS/src/client/MessageRouterClient.spec.ts
Tryouts/Messaging-JS/src/client/MessageRouterClient.ts
Tryouts/Messaging/Client/Client/MessageRouterClient.cs
Tryouts/Messaging/IntegrationTests/WebSocketEndToEndTests.cs

The .NET client is now processing messages synchronously, each subscriber having its own async message queue.
The JS client never had this issue, but now it's proven by tests.

Message Router - eliminate deadlocks and blockig in the message processing pipeline

---

.github/workflows/continuous-integration-prototypes.yml
.github/workflows/continuous-integration.yml

These changes are allowing the CI build to pick up all the solutions both in the src and the Tryouts folders.

Fix dotnet build for CI Jobs

---

Tryouts/Plugins/ApplicationPlugins/process explorer/package.json
Tryouts/package-lock.json

Removed Codelyzer from Process Explorer frontend because we don't need it and it's vulnerable to Cross-site-scripting (CVE-2021-4231)

Remove codelyzer from Process Explorer

---

Tryouts/Messaging/Client/Client/Abstractions/IConnection.cs
Tryouts/Messaging/Client/Client/MessageRouterClient.cs
Tryouts/Messaging/Client/Client/WebSocket/WebSocketConnection.cs
Tryouts/Messaging/Client/MorganStanley.ComposeUI.Messaging.Client.csproj
Tryouts/Messaging/Core/Exceptions/ThrowHelper.cs
Tryouts/Messaging/Core/MessageRouterException.cs
Tryouts/Messaging/IntegrationTests/WebSocketEndToEndTests.cs
Tryouts/Messaging/Server.Tests/MessageRouterServer.WebSocket.Tests.cs
Tryouts/Messaging/Server/Server/Abstractions/IClientConnection.cs
Tryouts/Messaging/Server/Server/MessageRouterServer.cs
Tryouts/Messaging/Server/Server/WebSocket/WebSocketConnection.cs
Tryouts/Plugins/ApplicationPlugins/ComposeUI.Example.DataService/Program.cs
Tryouts/Prototypes/ModulesPrototype/manifest.json

More consistent handling of errors when the connection drops from either side.
To validate, run the modules prototype and start exiting/killing modules.
Errors should be logged on the server only when the client is killed without properly closing the connection. The server should not crash in either case.

Message Router - better error handling, handle disconnected clients

---

src/shell/dotnet/Shell.sln
src/shell/dotnet/Shell/WebWindowOptions.cs
src/shell/dotnet/tests/Shell.Tests/CommandLineParserAttributedPropertyTests.cs
src/shell/dotnet/tests/Shell.Tests/CommandLineParserCustomPropertyDoubleTests.cs
src/shell/dotnet/tests/Shell.Tests/CommandLineParserCustomPropertyStringTests.cs
src/shell/dotnet/tests/Shell.Tests/CommandLineParserSimpleDoubleTests.cs
src/shell/dotnet/tests/Shell.Tests/CommandLineParserSimpleStringTests.cs
src/shell/dotnet/tests/Shell.Tests/Shell.Tests.csproj
src/shell/dotnet/tests/Shell.Tests/Usings.cs

Added tests for CommandLineParser
Changed WebViewOptions to handle default values by itself

Add CommandLineParser tests

---

.github/workflows/deploy-to-npm.yml
Tryouts/Plugins/ApplicationPlugins/defaultApp/package.json
Tryouts/Plugins/ApplicationPlugins/process explorer/package.json
examples/js-chart/package.json
examples/js-datagrid/package.json
package-lock.json
src/messaging/js/composeui-messaging-client/package.json
src/shell/js/composeui-node-launcher-example/package.json
src/shell/js/composeui-node-launcher/package.json

* Trigger: published release (manually on web ui)
* Pre-requisite: Successful Binary Publish to Tagged Release Assets
* Setting the node packages that we don't want to release for now to *"private": true*
* Adding script to deploy @morgan-stanley/composeui-node-launcher to NPM
Note: Setting the version numbers for packages to 0.1.0-alpha.1 will be a separate PR.
Expectation: only @morgan-stanley/composeui-node-launcher is deployed to NPM

Github Action: Deploy ready-to-release packages to NPM

---

.github/workflows/deploy-to-npm.yml
.github/workflows/release.yml

* The release job calls deploy-to-npm instead of trigger
* Sufficient permissions are granted to the Release workflow so it can upload the asset file
* Trigger for Release: Manually created release on the web UI

Github Actions: Fix Release and deploy-to-npm

---

package-lock.json
src/messaging/js/composeui-messaging-client/package.json
src/messaging/js/composeui-messaging-client/tsconfig.base.json
src/shell/js/composeui-fdc3/README.md
src/shell/js/composeui-fdc3/package.json
src/shell/js/composeui-fdc3/src/ComposeDesktopAgent.ts
src/shell/js/composeui-fdc3/src/index.ts
src/shell/js/composeui-fdc3/tsconfig.json

Also some minor consistency changes

Added skeleton project for fdc desktop agent TS implementation

---

prototypes/multi-module-prototype/examples/multi-module-example/ComposeUI.Example.DataService/MonthlySalesDataService.cs
src/messaging/dotnet/src/Client/Client/MessageRouterClient.cs
src/messaging/dotnet/src/Client/MessageRouterClientExtensions.cs
src/messaging/dotnet/src/Core/IMessageRouter.cs
src/messaging/dotnet/src/Core/Internal/Disposable.cs
src/messaging/dotnet/src/Core/MessageRouterExtensions.cs
src/messaging/dotnet/test/Client.Tests/Client/MessageRouterClient.Tests.cs

Added the `Topic` extension method for obtaining an `IAsyncObservable` for a given topic.

`Topic` extensions for Message Router client

---

src/messaging/dotnet/Messaging.sln
src/messaging/dotnet/src/Client/Client/Abstractions/IConnection.cs
src/messaging/dotnet/src/Client/Client/WebSocket/MessageRouterBuilderWebSocketExtensions.cs
src/messaging/dotnet/src/Client/MessageRouterClientExtensions.cs
src/messaging/dotnet/src/Host/Client/Internal/InProcessConnection.cs
src/messaging/dotnet/src/Host/Client/Internal/MessageRouterBuilderInProcessExtensions.cs
src/messaging/dotnet/src/Host/MorganStanley.ComposeUI.Messaging.Host.csproj
src/messaging/dotnet/src/Server/DependencyInjection/MessageRouterServerBuilder.cs
src/messaging/dotnet/src/Server/DependencyInjection/ServiceCollectionMessageRouterServerExtensions.cs
src/messaging/dotnet/src/Server/Server/MessageRouterServer.cs
src/messaging/dotnet/src/Server/Server/WebSocket/MessageRouterServerBuilderWebSocketExtensions.cs
src/messaging/dotnet/test/Host.Tests/Client/Internal/InProcessConnection.Tests.cs
src/messaging/dotnet/test/Host.Tests/GlobalUsings.cs
src/messaging/dotnet/test/Host.Tests/MorganStanley.ComposeUI.Messaging.Host.Tests.csproj
src/messaging/dotnet/test/IntegrationTests/EndToEndTestsBase.cs
src/messaging/dotnet/test/IntegrationTests/InProcessEndToEndTests.cs
src/messaging/dotnet/test/IntegrationTests/MorganStanley.ComposeUI.Messaging.IntegrationTests.csproj
src/messaging/dotnet/test/IntegrationTests/WebSocketEndToEndTests.cs
src/shell/dotnet/Shell.sln
src/shell/dotnet/Shell/App.xaml.cs
src/shell/dotnet/Shell/Shell.csproj

Added Messaging.Host packge with in-process connection implementation

In-process Message Router

---

src/messaging/dotnet/Directory.Build.props
src/messaging/dotnet/src/Client/Client/Abstractions/IConnection.cs
src/messaging/dotnet/src/Client/Client/Abstractions/IConnectionFactory.cs
src/messaging/dotnet/src/Client/Client/MessageRouterClient.cs
src/messaging/dotnet/src/Client/Client/WebSocket/MessageRouterBuilderWebSocketExtensions.cs
src/messaging/dotnet/src/Client/Client/WebSocket/WebSocketConnectionFactory.cs
src/messaging/dotnet/src/Core/Protocol/Json/MessageBufferConverter.cs
src/messaging/dotnet/src/Host/Client/Internal/InProcessConnection.cs
src/messaging/dotnet/src/Host/Client/Internal/InProcessConnectionFactory.cs
src/messaging/dotnet/src/Host/Client/Internal/MessageRouterBuilderInProcessExtensions.cs
src/messaging/dotnet/src/Server/Server/Abstractions/IClientConnection.cs
src/messaging/dotnet/src/Server/Server/MessageRouterServer.cs
src/messaging/dotnet/src/Server/Server/WebSocket/WebSocketConnection.cs
src/messaging/dotnet/test/Client.Tests/Client/MessageRouterClient.Tests.cs
src/messaging/dotnet/test/Server.Tests/Server/MessageRouterServer.Tests.cs
src/messaging/dotnet/test/Server.Tests/TestUtils/MockClientConnection.cs

Added IConnectionFactory for correctly implementing disposable pattern

Messaging: Added IConnectionFactory for correctly implementing disposable pattern

---

src/messaging/dotnet/src/Client/Client/WebSocket/WebSocketConnection.cs
src/messaging/dotnet/src/Core/MessageBufferJsonExtensions.cs
src/messaging/dotnet/src/Core/MorganStanley.ComposeUI.Messaging.Core.csproj
src/messaging/dotnet/src/Server/Server/WebSocket/WebSocketConnection.cs

...and use `ArrayPoolBufferWriter` instead

Remove dependency on RecyclableMemoryStream

---

package.json
src/shell/js/composeui-fdc3/package.json

The fdc3 project was missing from the lerna project.
The composeui-messaging-client reference pointed to a specific version instead of the monorepo project.

Fix lerna build for fdc3 js project

---

.github/dependabot.yml

Since dependabot doesn't support glob syntax it can't pick up the nuget dependencies in a multi-project repository easily.
This pull request adds the main projects under the src folder, and one prototype as a test.
Folders are specified for the project files.
I intend to add other projects later.
Tested on my fork

Chore(dependabot): Add nuget projects

---

prototypes/process-explorer/js/src/app/main-view/processes/processes.component.html
prototypes/process-explorer/js/src/app/main-view/processes/processes.component.ts
prototypes/process-explorer/js/src/app/services/mock-processes.service.ts
prototypes/process-explorer/js/src/app/services/mock-processes.ts

Adding back mock processes to benefit the upcoming frontend rewrite.
We'll create a new frontend project the commented out code is for reference only.

chore(process-explorer-frontend): Add back mock processes

---

examples/js-chart/chart.js
examples/js-chart/package.json
examples/js-datagrid/package.json
examples/js-datagrid/src/app/app.module.ts
examples/js-datagrid/src/app/main-view/datagrid/datagrid.component.spec.ts
examples/js-datagrid/src/app/main-view/services/mock-data.service.spec.ts
examples/js-datagrid/src/app/main-view/services/mock-data.service.ts
examples/serve-chart-and-grid.ps1
package-lock.json
src/shell/js/composeui-fdc3/src/Fdc3ComposeUI.spec.ts

Updated example projects to use FDC3 standard.

Updated Chart and DataGrid examples to use FDC3 standard

---

src/fdc3/dotnet/AppDirectory/AppDirectory.sln
src/fdc3/dotnet/AppDirectory/src/AppDirectory/AppDirectory.cs
src/fdc3/dotnet/AppDirectory/src/AppDirectory/AppDirectory.csproj
src/fdc3/dotnet/AppDirectory/src/AppDirectory/AppDirectoryOptions.cs
src/fdc3/dotnet/AppDirectory/src/AppDirectory/AppNotFoundException.cs
src/fdc3/dotnet/AppDirectory/src/AppDirectory/DependencyInjection/ServiceCollectionAppDirectoryExtensions.cs
src/fdc3/dotnet/AppDirectory/test/AppDirectory.Tests/AppDirectory.GetApp.Tests.cs
src/fdc3/dotnet/AppDirectory/test/AppDirectory.Tests/AppDirectory.GetApps.Tests.cs
src/fdc3/dotnet/AppDirectory/test/AppDirectory.Tests/AppDirectory.Tests.csproj
src/fdc3/dotnet/AppDirectory/test/AppDirectory.Tests/GlobalUsings.cs
src/fdc3/dotnet/AppDirectory/test/AppDirectory.Tests/TestUtils.cs
src/shared/dotnet/MorganStanley.ComposeUI.Testing/TaskExtensions.cs

Initial AppDirectory implementation
Work in progress with the following outstanding items:

FDC3 AppDirectory implementation

---

prototypes/process-explorer/oss-frontend/src/app/app.module.ts
prototypes/process-explorer/oss-frontend/src/app/components/processes/processes.component.html
prototypes/process-explorer/oss-frontend/src/app/components/processes/processes.component.scss
prototypes/process-explorer/oss-frontend/src/app/components/processes/processes.component.spec.ts
prototypes/process-explorer/oss-frontend/src/app/components/processes/processes.component.ts

Changes in this PR:
Processes View: Processes can be sorted by clicking on the table column headers.

feat(process-explorer/frontend): Add sort to column headers

---

prototypes/process-explorer/oss-frontend/src/app/DTOs/Subsystems.ts
prototypes/process-explorer/oss-frontend/src/app/app-routing.module.ts
prototypes/process-explorer/oss-frontend/src/app/app.module.ts
prototypes/process-explorer/oss-frontend/src/app/components/subsystems/subsystems.component.html
prototypes/process-explorer/oss-frontend/src/app/components/subsystems/subsystems.component.scss
prototypes/process-explorer/oss-frontend/src/app/components/subsystems/subsystems.component.spec.ts
prototypes/process-explorer/oss-frontend/src/app/components/subsystems/subsystems.component.ts
prototypes/process-explorer/oss-frontend/src/app/shared/sidenav/sidenav.component.html
prototypes/process-explorer/oss-frontend/src/app/shared/sidenav/sidenav.component.scss

- feat(process-explorer/frontend): Add Subsystems View

feat(process-explorer/frontend): Add Subsystems View

---

Directory.Packages.props

Changes in this Pull Request:
* Downgrading Moq to the last version without SponsorLink.

chore: Downgrade Moq to 4.18.4

---

src/fdc3/dotnet/DesktopAgent/src/DesktopAgent/Fdc3DesktopAgent.cs
src/fdc3/dotnet/DesktopAgent/tests/DesktopAgent.Tests/Fdc3DesktopAgentTests.cs
src/fdc3/dotnet/DesktopAgent/tests/DesktopAgent.Tests/Infrastructure/Internal/Fdc3DesktopAgentMessageRouterService.Tests.cs

Changes:
- Added pendingStartRequests collection to store the started module's vis raiseIntent call and wait for them to actually start before attempting to raiseIntent.

fix(fdc3) - Fixing flaky DesktopAgent tests

---

.github/workflows/release.yml

* Lerna picks up the versions from the package.json and publishes the packages that are not private. For more info: https://lerna.js.org/docs/features/version-and-publish#from-package
* tested on my fork for syntax errors

chore(github-actions/release): configure lerna to publish public packages

---

.github/workflows/continuous-integration.yml
.github/workflows/release.yml
package.json
src/fdc3/js/composeui-fdc3/package.json
src/messaging/js/composeui-messaging-client/package.json
src/shell/js/composeui-node-launcher/package.json

Add npm package provenance, modified package.json files to contain repository and publish information.
Based on the documentation: https://docs.npmjs.com/generating-provenance-statements#using-third-party-package-publishing-tools using 3rd party libraries (Lerna) to publish we should define EITHER an environment variable (NPM_CONFIG_PROVENANCE) OR add publish configs to the package.json files OR add a .npmrc file where we can set the provenance to true.
Based on the release https://github.com/lerna/lerna/releases/tag/6.6.2 : Lerna does support provenance from the 6.6.2 version. We are on the 8.1.2.
FYI: https://github.com/lerna/lerna/issues/3657 ;
I added package.json reporitory and publishConfigs and environment variable as well to be sure that the provenance flag is set.

feat(npm-provenance) - Update to Node.js 20 and add npm package provenance

---

.github/workflows/README.md
.github/workflows/continuous-integration.yml
.github/workflows/release.yml
Directory.Build.props
build/dotnet-pack.ps1
build/dotnet-test.ps1
prototypes/process-explorer/dotnet/src/MorganStanley.ComposeUI.ProcessExplorer.Abstractions/MorganStanley.ComposeUI.ProcessExplorer.Abstractions.csproj
prototypes/process-explorer/dotnet/src/MorganStanley.ComposeUI.ProcessExplorer.Client/MorganStanley.ComposeUI.ProcessExplorer.Client.csproj
prototypes/process-explorer/dotnet/src/MorganStanley.ComposeUI.ProcessExplorer.Core/MorganStanley.ComposeUI.ProcessExplorer.Core.csproj
prototypes/process-explorer/dotnet/src/MorganStanley.ComposeUI.ProcessExplorer.Server/MorganStanley.ComposeUI.ProcessExplorer.Server.csproj
src/messaging/dotnet/src/Client/MorganStanley.ComposeUI.Messaging.Client.csproj
src/messaging/dotnet/src/Core/MorganStanley.ComposeUI.Messaging.Core.csproj
src/messaging/dotnet/src/Host/MorganStanley.ComposeUI.Messaging.Host.csproj
src/messaging/dotnet/src/Server/MorganStanley.ComposeUI.Messaging.Server.csproj
src/shared/dotnet/src/MorganStanley.ComposeUI.Utilities/MorganStanley.ComposeUI.Utilities.csproj

In order to publish the nuget packages I decided some streamlining on the dotnet build side is necessary. I separated the changes in 3 commits so they are easier to review and follow in the history.
I made the existing CI job to make use of the build scripts in the repository. This change is intended to have the ability to run the same build process locally.
I added variable usage for DOTNET_VERSION and NODE_VERSION so we don't have to adjust this across multiple workflow files. This needs to be set up on the main repo as well.
I adjusted the packaging scripts and projects so by default projects are not packaged, version is handled in a central location and packages are output in a central location. I enabled packaging for the Messaging libraries where necessary.
I added a deploy_to_nuget …

Publishing Messaging nuget packages and some related CI streamlining #560

---

Directory.Build.props

Adding metadata for including version and license

chore: 0.1.0-alpha.4 - Add common nuget metadata

---

src/messaging/dotnet/src/Client/MorganStanley.ComposeUI.Messaging.Client.csproj
src/messaging/dotnet/src/Core/MorganStanley.ComposeUI.Messaging.Core.csproj
src/messaging/dotnet/src/Host/MorganStanley.ComposeUI.Messaging.Host.csproj
src/messaging/dotnet/src/Server/MorganStanley.ComposeUI.Messaging.Server.csproj

* Adding description to nuget packages linking to the GitHub pages site.
* Adding ComposeUI tag

chore(Messaging): Add description and other meta to packages

---

package-lock.json
src/messaging/js/composeui-messaging-client/README.md
src/messaging/js/composeui-messaging-client/package.json
src/shell/js/composeui-node-launcher/package.json

* Bumping Release Ready NPM packages' version to 0.1.0-alpha.4
* Changing JS Messaging Client README title to have the package name.

0.1.0-alpha.4

---

.github/workflows/continuous-integration.yml

This is a test if Node.js 20 and .NET 6 is picked up from the repository variable on a feature branch.

Use Repository Variables for Node.js and dotnet version

---

architecture/adr-014-module-catalog.md
src/module-loader/dotnet/src/MorganStanley.ComposeUI.ModuleLoader.Abstractions/IModuleCatalog.cs
src/module-loader/dotnet/src/MorganStanley.ComposeUI.ModuleLoader.Abstractions/ModuleLoaderException.cs
src/module-loader/dotnet/src/MorganStanley.ComposeUI.ModuleLoader.Abstractions/ModuleNotFoundException.cs
src/module-loader/dotnet/src/MorganStanley.ComposeUI.ModuleLoader/AggregateModuleCatalog.cs
src/module-loader/dotnet/src/MorganStanley.ComposeUI.ModuleLoader/ModuleLoader.cs
src/module-loader/dotnet/src/MorganStanley.ComposeUI.ModuleLoader/MorganStanley.ComposeUI.ModuleLoader.csproj
src/module-loader/dotnet/src/MorganStanley.ComposeUI.ModuleLoader/Runners/NativeModuleRunner.cs
src/module-loader/dotnet/tests/MorganStanley.ComposeUI.ModuleLoader.Abstractions.Tests/MorganStanley.ComposeUI.ModuleLoader.Abstractions.Tests.csproj
src/module-loader/dotnet/tests/MorganStanley.ComposeUI.ModuleLoader.Abstractions.Tests/StartupContextTests.cs
src/module-loader/dotnet/tests/MorganStanley.ComposeUI.ModuleLoader.Tests/AggregateModuleCatalogTests.cs
src/module-loader/dotnet/tests/MorganStanley.ComposeUI.ModuleLoader.Tests/DependencyInjection/ServiceCollectionExtensionsTests.cs
src/module-loader/dotnet/tests/MorganStanley.ComposeUI.ModuleLoader.Tests/ModuleInstanceTests.cs
src/module-loader/dotnet/tests/MorganStanley.ComposeUI.ModuleLoader.Tests/ModuleLoaderTests.cs
src/module-loader/dotnet/tests/MorganStanley.ComposeUI.ModuleLoader.Tests/MorganStanley.ComposeUI.ModuleLoader.Tests.csproj
src/module-loader/dotnet/tests/MorganStanley.ComposeUI.ModuleLoader.Tests/Runners/NativeModuleRunnerTests.cs
src/module-loader/dotnet/tests/MorganStanley.ComposeUI.ModuleLoader.Tests/Runners/WebModuleRunnerTests.cs

Changes:
- picked up changes from branch and commits related to the ModuleLoader when it tries to register its ModuleCatalog https://github.com/morganstanley/ComposeUI/commit/89ec2d9e1f9be47df0cacfdbb4586d9405d0b332 && https://github.com/morganstanley/ComposeUI/commit/57ad7daab2f8e28d63b335562b7f8b2bdf20fe79
- fixed tests when it registers its modulecatalogs (mocking array of catalogs)
Please refer to the PR https://github.com/morganstanley/ComposeUI/pull/569 that I accidentally closed.
I copied all the review comments/suggestions that the PR received and resolved them if they were marked as Resolved.
Also please be aware that the previous PR is not merged into any branch!

fix(module-loader) - Fixed ModuleLoader behavior with multiple modulecatalogs

---

site/content/documentation/v0.1.0-alpha.4/message-router.mdx

Changes:
- Fixed gatsby highlights for Javascript codes as well

fix(messaging-documentation) - Fix Javascript Gatsby highlights

---

Directory.Packages.props
src/shell/dotnet/Shell/App.xaml.cs
src/shell/dotnet/Shell/ImageSource/ImageSourceProvider.cs
src/shell/dotnet/Shell/MainWindow.xaml
src/shell/dotnet/Shell/MainWindow.xaml.cs
src/shell/dotnet/Shell/Modules/ModuleService.cs
src/shell/dotnet/Shell/Shell.csproj
src/shell/dotnet/Shell/WebContent.xaml
src/shell/dotnet/Shell/WebContent.xaml.cs
src/shell/dotnet/Shell/WebContentPane.cs

- Add Infragistics XamDockManager-based docking implementation to the shell, based on https://github.com/lilla28/ComposeUI/tree/ig/test

Docking web modules with Infragistics DockManager

---

src/module-loader/dotnet/src/MorganStanley.ComposeUI.ModuleLoader.Abstractions/NativeManifestDetails.cs
src/shell/dotnet/Shell/MainWindow.xaml.cs
src/shell/dotnet/Shell/Modules/ModuleCatalog.cs
src/shell/dotnet/examples/module-catalog.json

- For native modules instead of treating relative paths as relative to the current working directory treat them as relative to the path of the module catalog json file

Fix handling relative paths in module manifests

---

src/layout-persistence/dotnet/LayoutPersistence.sln
src/layout-persistence/dotnet/src/MorganStanley.ComposeUI.LayoutPersistence/Abstractions/ILayoutPersistence.cs
src/layout-persistence/dotnet/src/MorganStanley.ComposeUI.LayoutPersistence/Abstractions/ILayoutSerializer.cs
src/layout-persistence/dotnet/src/MorganStanley.ComposeUI.LayoutPersistence/FileLayoutPersistence.cs
src/layout-persistence/dotnet/src/MorganStanley.ComposeUI.LayoutPersistence/MorganStanley.ComposeUI.LayoutPersistence.csproj
src/layout-persistence/dotnet/src/MorganStanley.ComposeUI.LayoutPersistence/Serializers/JsonLayoutSerializer.cs
src/layout-persistence/dotnet/src/MorganStanley.ComposeUI.LayoutPersistence/Serializers/XmlLayoutSerializer.cs
src/layout-persistence/dotnet/tests/MorganStanley.ComposeUI.LayoutPersistence.Tests/FileLayoutPersistenceTests.cs
src/layout-persistence/dotnet/tests/MorganStanley.ComposeUI.LayoutPersistence.Tests/JsonLayoutSerializerTests.cs
src/layout-persistence/dotnet/tests/MorganStanley.ComposeUI.LayoutPersistence.Tests/LayoutData.cs
src/layout-persistence/dotnet/tests/MorganStanley.ComposeUI.LayoutPersistence.Tests/MorganStanley.ComposeUI.LayoutPersistence.Tests.csproj
src/layout-persistence/dotnet/tests/MorganStanley.ComposeUI.LayoutPersistence.Tests/Window.cs
src/layout-persistence/dotnet/tests/MorganStanley.ComposeUI.LayoutPersistence.Tests/XmlLayoutSerializerTests.cs

As we discussed, the shell will decide how it would like to serialize and deserialize layout data and the layout data is also depends on the shell.
- Added the necessary interfaces
- Added FileLayoutPersistance
- Added json and xml serializer/deserializer

Basic layout persistence implementation.

---

README.md

chore(README): Update README with with steps for running the FDC3 Conformance Framework

---

.github/workflows/dependency-submission.yml

This workflow is collecting the Nuget Dependencies managed with CPM and updates the SBOM to the Dependency Graph API so that vulnerable dependencies can be picked up by Dependabot Alerts which then creates a PR to upgrade the vulnerable dependency.
The job is scheduled to run every day at 7PM ET and also can be run manually.
The component-detection-dependency-submission-action detects the dependencies after a build so it was necessary to add the minimal set of build steps to achieve a "quick build" before component detection.

chore(Workflows): Add workflow to update the Dependency Graph with CPM Nuget dependencies

---

Directory.Packages.props

FluentAssertions has changed the License Agreement from Apache 2.0 to a paid one since version 8.0.0, so we only allow the project to upgrade to major version 7.x.

chore(deps): Prevent Upgrades to FluentAssertions 8.0.0 or higher

---

.github/dependabot.yml

In this PR dependabot rules are introduced to prevent the creation of dependabot PRs with upgrades to FluentAssertions 8.0.0 or higher.

chore(workflows/dependabot): Prevent Upgrades to FluentAssertions 8.0.0 or higher

---

.github/workflows/continuous-integration.yml

This change allows the CI build to kick off on any open PR regardless of the target branch.
This ensures the code quality of our temporal feature/prototype branches.

chore(CI): Run CI for any Pull Request

---

examples/fdc3-chart-and-grid/serve-chart-and-grid.ps1

Since lerna@8.1.9 when we try to run the PS script "examples/fdc3-chart-and-grid/serve-chart-and-grid.ps1" that serves the example we get the following error:
```Run `npm audit` for details.
lerna notice cli v8.1.9
lerna ERR! ENOPKG `package.json` does not exist, have you run `lerna init`?```
In case of lerna@8.1.8 this didn't occurred.
Removing `Push-Location .` and `Set-Location $PSScriptRoot\.. ` has resolved the issue

fix(examples/fdc3-chart-and-grid): Remove Location Alterations from PS Script

---

examples/fdc3-pricing-and-chat/serve-pricing-and-chat.ps1
examples/fdc3-trade-simulator/serve-trading-simulation-apps.ps1
examples/js-chart-and-grid-messagerouter/serve-chart-and-grid.ps1

Since lerna@8.1.9 when we try to run the PS scripts that serve the examples we get the following error for each:
```Run `npm audit` for details.
lerna notice cli v8.1.9
lerna ERR! ENOPKG `package.json` does not exist, have you run `lerna init`?```
In case of lerna@8.1.8 this didn't occurred.
Removing `Push-Location .` and `Set-Location $PSScriptRoot\.. ` has resolved the issue

Fix example ps scripts

---

src/fdc3/js/composeui-fdc3/src/ComposeUIDesktopAgent.ts
src/fdc3/js/composeui-fdc3/src/infrastructure/ComposeUIContextListener.ts

- Removed `setTimeout` using from the `DesktopAgent` implementation when we wanted to call the `getCurrentContext` on the `Listener` object after we had returned it from the `addContextListener` API call or if the `context listener` is joining to a `user channel`

Using Promise.finally instead of setTimeout when returning ContextListener object

---

.github/workflows/continuous-integration.yml
.github/workflows/release.yml

Updated the `continuous-integration.yml` and `release.yml` files to use .NET version 8.0.x instead of 6.0.x. Adjusted the path for uploading shell binaries to `net8.0-windows`.

Update CI and release configs to .NET 8.0.x

---

.github/dependabot.yml
Directory.Packages.props
examples/fdc3-chart-and-grid/js-datagrid/package.json
examples/fdc3-pricing-and-chat/js-chat/package.json
examples/fdc3-pricing-and-chat/js-pricing/package.json
examples/fdc3-trade-simulator/js-order-book/package.json
package-lock.json
src/fdc3/js/composeui-fdc3/package.json

1. Conforming to FDC3 2.0 Standard
* Grid example in fdc3-chart-and-grid has been downgraded to 2.0.3
* The rest of the examples have been upgraded to the latest patch (2.0.3) while making sure that we only allow patch upgrades (~)
2. Preventing unintended upgrades via Dependabot
* Ignoring Upgrades to 2.1 packages for both NPM and Nuget eco-systems

Downgrade FDC3 Examples and Prevent Upgrades to 2.1 Packages

---

.github/workflows/README.md
.github/workflows/continuous-integration.yml
.github/workflows/release.yml
README.md
src/messaging/js/composeui-messaging-client/rollup.config.js
src/shell/js/composeui-node-launcher/src/cli/install.js
src/shell/js/composeui-node-launcher/src/launcher.ts

This PR upgrades packages and CI workflows to build on Node.js 22.
[Node.js 22 has replaced the 'assert' syntax with 'with'](https://github.com/nodejs/node/issues/51622)
which had an impact on the packaging for 2 of our libraries:
1. MessageRouter JS Client
2. Node.js Launcher
**Changes in this PR:**
* chore(composeui-node-launcher): Upgrade Node.js to v22
* chore(messaging/js-client): Upgrade to Node.js v22
* chore(workflows): Upgrade CI and Release workflows to Node.js v22
* chore(documentation): Update README Files to Reflect Node.js 22 Upgrade
* fix(node-launcher): Fix binary Filename

Node.js v22 Upgrade

---

site/package.json

Add package scope for consistency and best practice. While this is an app that can and never will be published, it is best to be consistent.

Add scope to site package name

---

.github/workflows/dependency-submission.yml

*Changes in this PR*
- Removing cron config until the fixes are provided by the vendor so that dependabot is not trying to add unnecessary package references when raising a dependency upgrade PR triggered by a security alert.
- Note: it's still possibly to run the job manually when we want to test it.

chore(github-actions/dependency-submission): Removing scheduled execution

---

src/shell/dotnet/src/Shell/Properties/launchSettings.json

* Fixed the path to the example module catalog as the Shell solution's been moved
* Chart and Grid launch option is updated to not contain the FDC3 AppD anymore

chore(Shell): Fix path to ModuleCatalog in launchSettings.json

---

.github/workflows/dependency-submission.yml

This is a workaround for the issues caused by https://github.com/advanced-security/component-detection-dependency-submission-action/issues/107
The DecorsFilter in reality isn't filtering anything because the tool is still capturing the necessary Nuget and Npm packages.
Tested on my fork before opening the PR to the main repository

chore(Workflows): Add detectorsFilter to dependency-submission workflow

---

.github/workflows/dependency-submission.yml

* Specify versions for .NET (v8) and Node.js (v22), so SBOMs are created on the intended build tooling

chore(workflows/dependency-submission): Create SBOM on .NET 8 and Node.js 22
