process explorer/angular.json, process explorer/src/app/master-view/master-view.module.ts, process explorer/src/app/master-view/processes/processes.component.html, process explorer/src/app/services/mock-processes.ts
Reverts morganstanley/ComposeUI#31
=> Revert "Processes tree grid"

process explorer/package-lock.json, process explorer/package.json
Reverts morganstanley/ComposeUI#34
=> Revert "Bump karma from 6.3.14 to 6.3.16 in /process explorer"

process explorer/package-lock.json
Reverts morganstanley/ComposeUI#32
=> Revert "Bump url-parse from 1.5.7 to 1.5.10 in /process explorer"

process explorer/backend/LocalCollector/Communicator/ICommunicator.cs, process explorer/backend/LocalCollector/Connections/IConnectionMonitor.cs, process explorer/backend/LocalCollector/IProcessInfoCollector.cs, process explorer/backend/LocalCollector/ProcessInfoCollectorData.cs, process explorer/backend/ProcessExplorer.sln, process explorer/backend/ProcessExplorer/IProcessInfoAggregator.cs, process explorer/backend/ProcessExplorer/ProcessInfoAggregator.cs, process explorer/backend/ProcessExplorer/Processes/Communicator/CollectorHandler.cs, process explorer/backend/ProcessExplorer/Processes/Communicator/IUIHandler.cs, process explorer/backend/ProcessExplorer/Processes/IProcessMonitor.cs, process explorer/backend/ProcessExplorer/Processes/Logging/SourceGeneratedLogMessages.cs, process explorer/backend/ProcessExplorer/Processes/ProcessInfo.cs, process explorer/backend/ProcessExplorer/Processes/ProcessInfoGeneratorWindows.cs, process explorer/backend/ProcessExplorer/Processes/ProcessInfoManager.cs, process explorer/backend/ProcessExplorer/Processes/ProcessMonitor.cs
**ProcessExplorer: collects the runtime information from the individual processes (ProcessInfoCollector will send to the backend), and watches the processes which are belonging to the Compose and continuously send update to the UI about any changes.**
- InfoAggregator aggregates the given/gotten data from processes (which are running under the Compose) and collects information about the processes, and ProcessMonitor is watching them, if the relevant processes are modified/terminated/created and sends updates to the UI.
=> Process Explorer -- InfoAggregator's functionality

src/AvaloniaShellApp/MorganStanley.ComposeUI.AvaloniaShellApp.csproj
fix provided by @nick-polyak-ms
=> Fix the CI build

Tryouts/Prototypes/Directory.Build.targets
This PR covers https://github.com/morganstanley/ComposeUI/issues/88 issue.
=> added Directory.Build.targets file for automatically creating the required folders for all prototypes

Tryouts/Core/Abstractions/README.md, Tryouts/Core/BasicModels/README.md, Tryouts/Core/README.md, Tryouts/Core/Utilities/README.md, Tryouts/Plugins/ApplicationPlugins/AnotherWpfApp/README.md, Tryouts/Plugins/ApplicationPlugins/AnotherWpfThemeReceiverApp/README.md, Tryouts/Plugins/ApplicationPlugins/SimpleWpfApp/README.md, Tryouts/Plugins/ApplicationPlugins/WpfThemeChooserApp/README.md, Tryouts/Plugins/ApplicationPlugins/WpfThemeDictionaries/README.md, Tryouts/Plugins/ApplicationPlugins/WpfThemeReceiverApp/README.md, Tryouts/Plugins/Services/CommunicationsServices/GrpcCommunicationsService/README.md, Tryouts/Plugins/Services/MessagingService/README.md, Tryouts/Plugins/Services/ThemingService/README.md, Tryouts/Plugins/Services/TimeService/README.md, Tryouts/Plugins/ViewViewModelPlugins/TimeViewModel/README.md, Tryouts/README.md, Tryouts/Visuals/Avalonia/VisualUtils/README.md, src/AvaloniaShellApp/README.md, src/Core/Abstractions/README.md, src/Core/BasicModels/README.md, src/Core/README.md, src/Core/Utilities/README.md, src/README.md, src/Visuals/Avalonia/VisualUtils/README.md
Updated readme.md files throughout the application clarifying the purpose of various folders and projects.
=> Update readme files

glossary/Application.md, glossary/ComposeApplication.md
Extended the glossary with what is a Compose Application
=> Extended glossary

architecture/adr-011-process-ownership.md
I prepared an initial ADR suggestion about process ownership in Compose. This is a first version that I'd like to give additional thought, so I only created it as a draft PR for now, but feel free to add your insights.
=> Discussion for ADR about process ownership

Tryouts/Plugins/ApplicationPlugins/datagrid/package.json, Tryouts/Plugins/ApplicationPlugins/datagrid/src/app/app.component.html, Tryouts/Plugins/ApplicationPlugins/datagrid/src/app/app.component.scss, Tryouts/Plugins/ApplicationPlugins/datagrid/src/app/main-view/datagrid/datagrid.component.html, Tryouts/Plugins/ApplicationPlugins/datagrid/src/app/main-view/datagrid/datagrid.component.scss, Tryouts/Plugins/ApplicationPlugins/datagrid/src/app/main-view/main-view.component.scss, Tryouts/Plugins/ApplicationPlugins/datagrid/src/app/main-view/main-view.module.ts, Tryouts/Plugins/ApplicationPlugins/datagrid/src/styles.scss, Tryouts/package-lock.json
Responsive layout:
- As creating a responsive design, it is allowed that the font size and table will scale up or down as the browser window is resized.
=> Reactive layout when resizing browser window

.github/workflows/release.yml
* Make Release Reusable so that deploy-to-npm can reuse it
=> Make Release Reusable

examples/fdc3-appdirectory/README.md, examples/fdc3-appdirectory/apps.json, examples/serve-chart-and-grid.ps1, src/fdc3/dotnet/AppDirectory/src/AppDirectory/AppDirectoryOptions.cs, src/fdc3/dotnet/DesktopAgent/src/DesktopAgent/DependencyInjection/Fdc3DesktopAgentBuilder.cs, src/fdc3/dotnet/DesktopAgent/src/DesktopAgent/DependencyInjection/Fdc3DesktopAgentOptions.cs, src/fdc3/dotnet/DesktopAgent/src/DesktopAgent/DependencyInjection/ServiceCollectionExtensions.cs, src/fdc3/dotnet/DesktopAgent/src/DesktopAgent/Fdc3DesktopAgent.cs, src/fdc3/dotnet/DesktopAgent/tests/DesktopAgent.Tests/EndToEndTests.cs, src/fdc3/dotnet/DesktopAgent/tests/DesktopAgent.Tests/Fdc3DesktopAgentTests.cs, src/shell/dotnet/Shell.sln, src/shell/dotnet/Shell/App.xaml.cs, src/shell/dotnet/Shell/Fdc3/Fdc3Options.cs, src/shell/dotnet/Shell/Properties/launchSettings.json, src/shell/dotnet/Shell/Shell.csproj, src/shell/dotnet/Shell/appsettings.json
Adds the AppDirectory to the Shell
Refactored configuration of FDC3-related services
=> AppDirectory+Shell integration

prototypes/process-explorer/oss-frontend/src/app/DTOs/SubsystemInfo.ts, prototypes/process-explorer/oss-frontend/src/app/services/subsystems-service/mock-subsystems.ts, prototypes/process-explorer/oss-frontend/src/app/services/subsystems-service/subsystems.service.spec.ts, prototypes/process-explorer/oss-frontend/src/app/services/subsystems-service/subsystems.service.ts
* feat(process-explorer/frontend): Add mock subsystems for the new frontend
=> feat(process-explorer/frontend): Add mock subsystems

architecture/adr-012-message-router.md
Fixed status since this ADR is superseding ADR-5
=> chore(ADR-12): Update Status

.github/workflows/continuous-integration.yml
Improved .NET build scripts so that they don't exit on the first error
Added environment variable to enable ANSI colors in build output
=> .NET build scripts

examples/fdc3-appdirectory/apps.json, src/fdc3/dotnet/DesktopAgent/src/DesktopAgent/Fdc3DesktopAgent.cs, src/fdc3/js/composeui-fdc3/src/Fdc3ComposeUI.spec.ts, src/fdc3/js/composeui-fdc3/src/infrastructure/ComposeUIErrors.ts, src/shell/dotnet/Shell/Properties/launchSettings.json, src/shell/dotnet/examples/module-catalog.json
- Add the FDC3 2.0 Conformance Framework to the module catalog and to the local AppDirectory JSON
- Use the local AppDirectory JSON for the Shell because the one hosted on finos.org does not conform to the standard
- Minor fixes:
- In Fdc3DesktopAgent don't throw an exception when we receive an invalid Guid
- Fix spelling in the TS code
=> Fdc3 conformance

site/content/alternatives.mdx, site/content/background.mdx, site/content/documentation-hero.mdx, site/content/documentation/examples.mdx, site/content/getting-started.mdx, site/content/hero.mdx, site/content/use-cases.mdx
Added the following mdx files:
- alternatives.mdx
- background.mdx
- getting-started.mdx
- hero.mdx
- use-cases.mdx
- documentation-hero.mdx
- examples.mdx
=> Added GitHub pages content

README.md
Changes in this PR:
- Updated readme with Development Prerequisites and Experimental Build Steps
=> Chore(Readme): Adding Prerequisites and experimental build steps

.github/dependabot.yml
https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/
=> Add dependency grouping for npm updates

.gitignore, site/package-lock.json, site/package.json
include --prefix-paths in build to fix #535
=> Fix documentation url in menu

src/fdc3/js/composeui-fdc3/package.json, src/shell/js/composeui-node-launcher/package.json
* chore: set @morgan-stanley/composeui-fdc3 package to private.
* chore: bump @morgan-stanley/composeui-node-launcher to 0.1.0-alpha.3
=> 0.1.0-alpha.3

src/messaging/js/composeui-messaging-client/src/client/MessageRouterClient.ts
- Added the missing delete of the topic from a local record when unsubscribing from the topic
- Synchronized subscribe and unsubscribe methods.
=> Synchronized subscribe and unsubscribe methods.

.github/dependabot.yml
Fixing indentation errors that unfortunately haven't been picked up by the web IDE for some reason.
=> chore(workflows/dependabot): Fix indentation for ignore rules

.github/dependabot.yml
* Fix syntax error in Dependabot ignore rules.
=> chore(dependabot): Fix ignore rules

.github/workflows/release.yml, Directory.Build.props, src/fdc3/js/composeui-fdc3/package.json, src/messaging/js/composeui-messaging-client/package.json, src/shell/js/composeui-node-launcher/package.json
Build-time folders have been missing from the NPM packages
=> 0.1.0-alpha.6
